### ISSUE TITLE
Fishermen page need to show all 13 fishermen ("People")

### ISSUE THREAD

**Issue by ldford** [Ecotrust/cfn.org#1]
This page should be showing 4 rows and 4 columns (currently showing 1 row, 4 columns):
http://fbb.416.myftpupload.com/fishermen/

See more in Pagebuilder, select "Members" template.

**Comment by gewgawn** [comment]
This is finished. Only four of the members were listed as such in the "categories" tab on their post page.

**Comment by ldford** [comment]
I love an easy fix. I’m not seeing where the categories tab is. Where do I list them as members? (for future management)
