### ISSUE TITLE
Links on the homepage Rev Slider take you to dev site

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/cfn.org#11]
On the homepage the all the slider links take you to the dev site. For example: ["Meet Our Fishermen"](http://www.communityfisheriesnetwork.org/) button takes you to the dev site. 

[<img width="60%" height="auto" alt="screen shot 2016-10-03 at 5 47 48 pm" src="https://cloud.githubusercontent.com/assets/2632164/19059071/a66963a2-8991-11e6-9b39-ebc908abd996.png">](http://fbb.416.myftpupload.com/fishermen/)

**Comment by ldford** [comment]
Yikes. Crazy. I fixed that, and I am trying to fix the weird wrapping of the button thing, but I'm not having luck in all browsers. Also, revolution slider is AWFUL and I'd really like to scrap it and have one photo with no slider. Talk about this sometime?

**Comment by pollardld** [comment]
For sure, revolution slider is the worst! 
One photo with no slider is refreshing to hear, lol. 

The button wrap issue was persisting becuase of media template's intense caching. I cleared the sites cache and the button wrap is fixed. If you ever make a change and wonder: 

> why is this not showing up?

The cache clear is at the top of the WP dashboard under Media Temple:  

<img width="80%" align="middle" alt="screen shot 2016-10-04 at 1 02 10 pm" src="https://cloud.githubusercontent.com/assets/2632164/19090446/5b700de0-8a33-11e6-9882-7576b83f64fa.png">

**Comment by ldford** [comment]
OMG thank you.
