### ISSUE TITLE
Site is... broken

### ISSUE THREAD

**Issue by ldford** [Ecotrust/cfn.org#12]
Front end has weird error message across top.
http://www.communityfisheriesnetwork.org/

When I try to access WP admin panel, I get this error message:
![image](https://cloud.githubusercontent.com/assets/6453589/22487837/de177b64-e7c3-11e6-9c49-f2e1a067d6f1.png)

**Comment by pollardld** [comment]
`Warning: ksort() expects parameter 1 to be array, object given in /home/content/p3pnexwpnas01_data03/86/2265986/html/wp-content/plugins/bbpress/includes/core/template-functions.php on line 316`
  

    `Warning: Cannot modify header information - headers already sent by (output started at /home/content/p3pnexwpnas01_data03/86/2265986/html/wp-content/plugins/bbpress/includes/core/template-functions.php:316) in /home/content/p3pnexwpnas01_data03/86/2265986/html/wp-includes/pluggable.php on line 1179`

**Comment by pollardld** [comment]
<img width="1397" alt="screen shot 2017-01-31 at 2 49 38 pm" src="https://cloud.githubusercontent.com/assets/2632164/22487990/8e60d9a2-e7c4-11e6-8d1c-1daccdfb8c56.png">
