### ISSUE TITLE
Fishermen individual pages ("People"): lefthand sidebar logo fix

### ISSUE THREAD

**Issue by ldford** [Ecotrust/cfn.org#2]
They lefthand logos on member pages are tiny: http://fbb.416.myftpupload.com/people/morro-bay-community-quota-fund/

Some of them were built too small and need to be rebuilt by a designer. But I think the space they are displayed in needs to be bigger too.

**Comment by gewgawn** [comment]
I made them 2.5 times larger. The logos are much more legible, but it makes for a lot of scrolling to get to the bottom. Let me know if you want them any larger.

**Comment by ldford** [comment]
Perfect.
