### ISSUE TITLE
Tags and categories in News

### ISSUE THREAD

**Issue by ldford** [Ecotrust/cfn.org#4]
Tags (San Francisco CFA) is showing in lefthand sidebar. Should it be at bottom of posts instead? Categories not showing up at all. What is your recommendation here?
http://fbb.416.myftpupload.com/fair-fish-on-san-francisco-fishermans-wharf/

**Comment by gewgawn** [comment]
For my money I would recommend leaving it as is. Your categories are used in part to distinguish your member pages, so I believe they would show up as well if your categories were displayed.

**Comment by ldford** [comment]
Sounds good!
