### ISSUE TITLE
Fatal error on single profile/people pages

### ISSUE THREAD

**Issue by ldford** [Ecotrust/cfn.org#9]

**Comment by ldford** [comment]
Clickthroughs to individual fisherman pages broken. e.g. http://www.communityfisheriesnetwork.org/people/alaska-jig-association/

Fatal error: Call to undefined function get_field() in /home/content/p3pnexwpnas01_data03/86/2265986/html/wp-content/themes/communityfisheries/single-cpt_people.php on line 21

**Comment by pollardld** [comment]
looking into this now.

**Comment by pollardld** [comment]
Im able to access the site in mediatemple, thanks!  

I may need to update some plugins and the wordpress core. Could you add me as an admin user for Wordpress? @ldford

**Comment by ldford** [comment]
Hey. You are added to CFN WP as an admin level user. Is that what you mean?

**Comment by pollardld** [comment]
That is what I meant. Thought we had already done that. I guess wordpress is acting up. I haven't been able to login. I tried to reset my password, but still have not received the email to update it. 

I Will wait a few and try again.

**Comment by pollardld** [comment]
The password reset went to my junk mail! First time that has happened. Sorry for the confusion.

**Comment by pollardld** [comment]
Activated the advanced custom fields plugin to fix. 
Do you know why the plugin was deactivated? @ldford 

http://www.communityfisheriesnetwork.org/people/alaska-jig-association/

**Comment by ldford** [comment]
No idea. It must have been either me or Megan, but I really have no memory of ever having deactivated a plugin on any website ever! Thanks for the fix.

**Comment by pollardld** [comment]
no worries. The deactivation could have been a number of reasons. Just checking if it needed to stay deactivated.
